### ISSUE TITLE
Program results

### ISSUE THREAD

**Issue by En-lightener** [mivp-agent/moos-ivp-agent#16]
Hello, could you please tell me the results of AgentAquaticusDemo.gif and DebuggingDemo.gif and DiscretizerDemo.gif and QTableDemo.gif and TestingDemo.gif to input which commands can be run? Can you provide the running instructions?

**Comment by CarterFendley** [comment]
Hi @En-lightener, for all of these you should be running the commands specified in the docker container. You can get a terminal on the docker container by `./docker.sh connect` (after previously running `./docker.sh run`). All the UI elements are forwarded to the host machine via X11 (you won't see anything at all if that is not properly setup) there are some MacOS specific notes in the main README about that. Below is information on each of those.

---

The `AgentAquaticusDemo.gif` was produced by running the [examples/QTable](https://github.com/mivp-agent/moos-ivp-agent/tree/main/examples/QTable) example through the `./test.sh` script. There are a few modifications required to get the simulation to show up graphically, namely [here](https://github.com/mivp-agent/moos-ivp-agent/blob/97ee296a8fff1ba22b1d7aec9526ad57394fe215/examples/QTable/scripts/sim_launch.sh#L6-L7) and [here](https://github.com/mivp-agent/moos-ivp-agent/blob/97ee296a8fff1ba22b1d7aec9526ad57394fe215/examples/QTable/scripts/sim_launch.sh#L29-L30), uncomment the below and comment the lines above so that it looks like the following.

```bash
# TIME_WARP="10"
TIME_WARP="1"
```
```bash
#   ./launch_shoreside.sh --no_gui $LOGGING $TIME_WARP >& /dev/null &
  ./launch_shoreside.sh $LOGGING $TIME_WARP >& /dev/null &
```

---

The `DebuggingDemo.gif` was produced by running the [examples/pLearn](https://github.com/mivp-agent/moos-ivp-agent/tree/main/examples/pLearn) example which allows for backwards compatibility with previous ML tooling. There are details in that README, to get the graphs shown in the GIF to appear you need to add `--debug` For example you could use:
```bash
./run.sh --model model/trained/topModel/model/ --debug
```

---

The `DiscretizerDemo.gif` was produced by running the [examples/DiscreteField](https://github.com/mivp-agent/moos-ivp-agent/tree/main/examples/DiscreteField) demo. There is a `README.md` in that folder with extensive information on it.

---

The `AgentAquaticusDemo.gif` was produced by running the [examples/QTable](https://github.com/mivp-agent/moos-ivp-agent/tree/main/examples/QTable) example through the `./run.sh` script. No additional modifications should be needed to run that one.

-- -

The `TestingDemo.gif` was produced by running [examples/pLearn](https://github.com/mivp-agent/moos-ivp-agent/tree/main/examples/pLearn) examples. You will have to run the commands listed below.

**NOTE:** That GIF is *extremely* speed up.

```bash
./model/test.py
# AND in a separate terminal
./model/scripts/launch_sim.sh
```

**Comment by CarterFendley** [comment]
Good questions, closing since it seems there was no followup questions.
